# Generated by Django 3.0.7 on 2020-09-26 08:17

from django.db import migrations, models
import uuid
import uuid_upload_path.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to=uuid_upload_path.storage.upload_to)),
                ('status', models.CharField(default='ADDED', max_length=20)),
            ],
            options={
                'verbose_name': 'product file',
                'verbose_name_plural': 'product files',
                'ordering': ('-created_at',),
            },
        ),
    ]
