# Generated by Django 3.0.7 on 2020-09-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFile',
        ),
    ]
